title: Streamdata Gallery Azure Data Lake Store
url: azure-data-lake-store.streamdata.gallery
tag: Azure Data Lake Store
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: azure-data-lake-store
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
